name: "Terraform CI/CD"

# Trigger: Run this pipeline every time we push code to the 'main' branch
on:
    push:
        branches:
            - main
permissions:
    contents: read

jobs:
    terraform:
        name: "Terraform Apply"
        runs-on: ubuntu-latest

        # Load the secrets we saved in GitHub Settings
        env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_REGION: ca-central-1
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            #install Terraform
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.0
            # 3. Initialize
            - name: Terraform Init
              run: terraform init
            
            # 4. Check formatting
            - name: Terraform Format
              run: terraform fmt -check
            
            # 5. Apply changes
            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve
